In [1]:
import pandas
import numpy

In [2]:
file1 = pandas.read_csv('Assignment-2-CleanedData.csv')

In [ ]:
file1.drop('Unnamed: 0', axis=1, inplace = True)

In [5]:
from fuzzywuzzy import fuzz
from fuzzywuzzy import process
import pandas_datareader as pdr
import datetime as dt

In [6]:
import requests
import json
import urllib

def get_TickerSymbol(companyName):
    url = "http://d.yimg.com/autoc.finance.yahoo.com/autoc?query={}&region=1&lang=en".format(companyName)

    result = requests.get(url).json()
    
    for x in result['ResultSet']['Result']:
                    return x['symbol']
        

arrTicker=[]
comp_name = file1.Entity

    
for  name in comp_name:
    arrTicker.append(get_TickerSymbol(name))
    
    
print(arrTicker)

['AOL-U.TI', 'ADP', None, 'CIT-U.TI', None, 'HPQ', None, 'KDDIY', None, 'AOL-U.TI', None, None, None, 'GPS', None, None, None, None, None, 'AMTD', 'FIS', 'DNPCF', None, None, None, None, None, 'AT', 'SBUX', None, None, None, '^UMIAMIFL', None, None, None, None, None, None, None, None, None, None, None, None, 'LYNS', None, None, 'IGRW', None, None, None, None, 'HTLD', None, 'AT', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'PPB.L', 'JPM-PB', None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'CIT-U.TI', None, None, 'GB00B1Z54R10.L', None, None, None, 'MBSS.JK', None, None, None, None, None, None, None, 'NHS', None, None, None, '600488.SS', '200771.SZ', None, None, None, None, None, None, None, None, None, 'GPN', None, None, None, None, None, 'KTC.DU', None, None, 'ATVI', None, None, None, None, 'KCT.V', 'K55306BA2822.KS', None, None, None, None, None, None, 'CIT-U.TI', None, None, '2GF.F', 'NTDOY', 'TWTR', 'AAPL', None, None, 'NMBS.KL', None, None, None, 'VOD', None, None, None, 'FB', 'YAHOY', 'ADBE', None, None, 'AABA', None, None, 'NDAQ', None, 'JAPSY', None, None, 'D', None, 'SPLS', None, 'UPS', 'CYH', None, None, None, None, 'AOL-U.TI', 'HD', 'TGT', 'JPM-PB', 'EBAY', 'AABA', None, None, 'IRS', 'TALK.L', 'MSPYX', None, None, None, None, None, 'CPWFF8.EX', 'SJ8.MU', None, None, '0303.HK', None, None, None, None, None, None, None, None, None, None, None, 'FLINGX', None, None, 'ANTM', 'VKTX', None, None, None, None, None, None, None, None, 'DGX', 'ATGYX', None, None, None, None, None, None, '1880.HK', None, None, None, None, '035080.KQ', None, 'AABA', None, None, None, None, None, None, '^CEX', None, None, 'EFX', None]

In [8]:
start = dt.datetime(2004,1,1)
end = dt.datetime(2017,6,6)
panel_data = pdr.DataReader(arrTicker, 'yahoo', start, end)

/Users/agasthya/anaconda3/lib/python3.6/site-packages/pandas_datareader/yahoo/daily.py:136: SymbolWarning: Failed to read symbol: 'AOL-U.TI', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
/Users/agasthya/anaconda3/lib/python3.6/site-packages/pandas_datareader/yahoo/daily.py:136: SymbolWarning: Failed to read symbol: None, replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
/Users/agasthya/anaconda3/lib/python3.6/site-packages/pandas_datareader/yahoo/daily.py:136: SymbolWarning: Failed to read symbol: 'CIT-U.TI', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
/Users/agasthya/anaconda3/lib/python3.6/site-packages/pandas_datareader/yahoo/daily.py:136: SymbolWarning: Failed to read symbol: '^UMIAMIFL', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
/Users/agasthya/anaconda3/lib/python3.6/site-packages/pandas_datareader/yahoo/daily.py:136: SymbolWarning: Failed to read symbol: 'JPM-PB', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
/Users/agasthya/anaconda3/lib/python3.6/site-packages/pandas_datareader/yahoo/daily.py:136: SymbolWarning: Failed to read symbol: 'KCT.V', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
/Users/agasthya/anaconda3/lib/python3.6/site-packages/pandas_datareader/yahoo/daily.py:136: SymbolWarning: Failed to read symbol: 'NMBS.KL', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
/Users/agasthya/anaconda3/lib/python3.6/site-packages/pandas_datareader/yahoo/daily.py:136: SymbolWarning: Failed to read symbol: 'CPWFF8.EX', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
/Users/agasthya/anaconda3/lib/python3.6/site-packages/pandas_datareader/yahoo/daily.py:136: SymbolWarning: Failed to read symbol: 'FLINGX', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)
/Users/agasthya/anaconda3/lib/python3.6/site-packages/pandas_datareader/yahoo/daily.py:136: SymbolWarning: Failed to read symbol: '1880.HK', replacing with NaN.
  warnings.warn(msg.format(sym), SymbolWarning)

In [9]:
panel_data

<class 'pandas.core.panel.Panel'>
Dimensions: 6 (items) x 3499 (major_axis) x 62 (minor_axis)
Items axis: Adj Close to Volume
Major_axis axis: 2004-01-01 00:00:00 to 2017-06-07 00:00:00
Minor_axis axis: ADP to 1880.HK

In [10]:
# The index in this DataFrame is the major index of the panel_data.
finalData = panel_data.ix['Close']

# Getting all weekdays between 01/01/2000 and 12/31/2016
all_weekdays = pandas.date_range(start=start, end=end, freq='B')

# How do we align the existing prices in adj_close with our new set of dates?
# All we need to do is reindex close using all_weekdays as the new index
finalData = finalData.reindex(all_weekdays)
finalData.head(10)

/Users/agasthya/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

,ADP,HPQ,KDDIY,GPS,AMTD,FIS,DNPCF,AT,SBUX,LYNS,...,AOL-U.TI,None,CIT-U.TI,^UMIAMIFL,JPM-PB,KCT.V,NMBS.KL,CPWFF8.EX,FLINGX,1880.HK
2004-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2004-01-02,31.690842,10.517712,NaN,22.530001,14.15,32.939999,NaN,NaN,8.2275,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2004-01-05,32.626656,10.749319,NaN,22.610001,14.88,33.939999,NaN,NaN,8.3525,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2004-01-06,32.935951,10.794732,NaN,23.100000,15.00,33.599998,NaN,NaN,8.4550,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2004-01-07,32.761478,10.608538,NaN,23.000000,15.14,33.549999,NaN,NaN,8.4200,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2004-01-08,32.698032,11.212534,NaN,20.000000,14.78,32.919998,NaN,NaN,8.3450,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2004-01-09,31.952553,10.971844,NaN,19.850000,14.85,33.020000,NaN,NaN,8.2750,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2004-01-12,31.857384,11.207993,NaN,19.850000,15.18,33.480000,NaN,NaN,8.3400,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2004-01-13,31.801870,11.017257,NaN,19.860001,15.12,33.349998,NaN,NaN,8.2775,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2004-01-14,32.531490,11.217075,NaN,20.450001,15.30,33.500000,NaN,NaN,8.4075,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
finalData2 = finalData.T

In [45]:
finalData2 = finalData.groupby(pandas.TimeGrouper(freq='12M')).mean()

In [50]:
finalData2 = finalData2.T

,2004-01-31 00:00:00,2005-01-31 00:00:00,2006-01-31 00:00:00,2007-01-31 00:00:00,2008-01-31 00:00:00,2009-01-31 00:00:00,2010-01-31 00:00:00,2011-01-31 00:00:00,2012-01-31 00:00:00,2013-01-31 00:00:00,2014-01-31 00:00:00,2015-01-31 00:00:00,2016-01-31 00:00:00,2017-01-31 00:00:00,2018-01-31 00:00:00
ADP,32.813820,34.064935,35.050695,36.863325,40.408635,35.680073,33.713959,37.884942,45.168799,49.372064,62.635004,73.676731,84.028088,90.823439,101.266322
HPQ,11.182107,9.282525,11.431419,16.083477,21.027115,19.370576,18.872159,20.788701,15.047071,8.861357,10.792335,15.770325,13.679339,13.505929,17.734483
KDDIY,NaN,NaN,NaN,NaN,NaN,5.760977,4.477570,4.312767,5.716693,5.705365,8.373545,9.948712,11.916003,14.199206,13.273333
GPS,20.274500,21.430397,19.620000,18.361594,18.685913,16.659802,17.703267,20.624862,19.291825,30.194582,39.342302,40.946255,34.085259,24.304087,24.133908
AMTD,15.622000,12.953095,17.794405,17.797131,18.087817,16.548333,17.460120,17.583518,18.069206,17.205378,25.242143,32.671235,35.333307,33.768696,39.345977
FIS,33.138000,36.033690,37.356429,38.406175,47.072698,26.872619,21.373426,26.716403,28.846270,33.051315,45.097143,56.455100,65.283984,72.799526,82.131494
DNPCF,NaN,NaN,NaN,NaN,NaN,NaN,24.251488,25.450751,22.227381,16.145100,18.625317,19.221594,20.064143,19.887906,20.223448
AT,NaN,NaN,NaN,NaN,NaN,NaN,10.955897,12.962095,14.711349,13.601873,4.833968,2.964542,2.473267,2.390079,2.474138
SBUX,8.636375,11.504315,13.505823,17.776215,13.474345,7.209841,8.390398,13.453913,19.505853,25.950040,34.538433,38.089821,54.574681,56.521028,58.449425
LYNS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.345833,0.807193,0.139371,0.114967,0.066400,0.005652,0.008005,0.008000
IGRW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.307358,3.568446,0.027292,0.016443,0.001000,0.000337,NaN
HTLD,12.017250,13.523552,15.038810,16.541484,15.582698,15.174683,14.635896,15.562609,15.298333,13.867171,15.145436,23.254303,20.785936,18.952925,19.962874
PPB.L,592.283282,832.894813,1515.891835,1570.373521,2457.813280,2209.452233,2037.530749,2940.200863,2061.183005,2005.375434,2369.234735,3025.485793,6801.448655,8962.520473,8525.174419
GB00B1Z54R10.L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.268818,1.356902,1.475867
MBSS.JK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1402.673267,1101.869919,1086.934156,1110.000000,591.139918,316.078838,413.506024
NHS,16.071500,15.623373,15.344286,14.494741,13.931746,9.483611,9.724343,13.273123,13.757460,14.104940,13.424246,13.238406,11.278765,11.114150,11.924598
600488.SS,2.123775,2.406986,1.873905,2.522458,5.920895,5.137517,5.382891,5.858151,5.269447,3.721532,4.557364,4.983702,7.223021,6.103816,6.040723
200771.SZ,1.966550,2.128782,2.932172,3.968178,9.204711,4.761003,6.274427,9.051976,8.731099,8.632742,11.364644,8.869534,13.958930,9.066793,7.992048
GPN,12.090875,12.244167,18.282827,22.372689,20.156429,20.798552,20.660299,21.029624,23.701944,22.541813,26.366706,36.880219,56.120139,71.584229,82.068161
KTC.DU,15.295238,15.033813,17.048132,17.704427,17.285516,13.046160,10.473629,15.021284,12.645058,11.396928,11.843087,11.351821,11.604179,12.927795,14.853529
ATVI,3.459375,4.336756,6.875998,7.058964,10.364782,13.908373,11.282869,11.324229,11.752937,11.780837,15.909127,20.838885,28.842351,38.146561,50.148391
K55306BA2822.KS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,996.272499,1001.829731,NaN
2GF.F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.730577,0.414558,0.123178,0.029996,0.007642,0.009451,0.015126
NTDOY,12.180000,13.675913,14.055397,23.614303,54.148056,56.985119,33.589402,35.747273,24.252540,15.385219,14.567262,13.982032,19.896295,24.307431,29.973103
TWTR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53.975345,43.530518,33.848566,17.441423,16.387471
AAPL,1.628678,2.800831,7.157752,10.241833,19.153662,19.460459,22.292686,38.566522,53.023271,83.036505,67.990975,95.024644,119.152988,106.250830,143.168390
VOD,31.031309,28.588626,29.382577,25.398224,33.282122,26.515218,20.853995,24.425548,27.999288,28.001227,32.650640,34.843841,34.413586,29.638735,26.549310
FB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.348295,37.697500,70.386653,90.505937,119.164941,142.324598
YAHOY,NaN,NaN,NaN,NaN,NaN,NaN,7.109187,7.405605,6.693151,6.645130,10.073772,8.728606,8.095697,8.288103,9.060115
ADBE,19.025500,23.892837,31.566151,35.627809,41.782699,34.066111,29.714462,31.030751,29.865437,33.355657,48.601349,68.428645,82.304104,98.953794,128.328851
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
JAPSY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.930460,16.179119,15.622241
D,31.394750,32.290099,37.786012,38.437430,44.237123,41.035397,33.844542,41.798577,48.296706,52.189004,60.439087,70.914701,70.279084,73.828656,77.040690
SPLS,17.421300,19.206939,21.836479,24.889084,24.129445,23.682460,21.066708,21.742559,23.172193,52.375897,90.334287,74.203766,49.107921,33.987550,27.802414
UPS,72.591500,74.770833,73.008691,76.269841,72.929643,62.813572,52.987530,65.704545,70.919365,76.027052,90.327262,101.358526,99.483506,107.661146,106.207127
CYH,23.540083,22.072839,30.052473,30.088703,29.237505,23.352223,22.600771,28.518570,20.838646,21.864937,35.538403,38.388100,37.612723,11.198308,8.800920
HD,35.471000,37.682222,40.056429,38.205060,35.009405,25.331310,25.422151,31.797391,36.795714,55.272510,75.741905,87.357091,117.890040,130.796798,148.893563
TGT,38.162000,45.924206,53.296627,53.445179,60.269524,46.195754,42.266056,53.946996,50.786786,59.816614,66.272976,62.767251,77.874303,73.270791,57.186207
EBAY,13.893729,18.425609,16.617414,13.418464,14.107176,9.733947,8.130257,10.553027,13.200641,18.553865,22.474914,22.538164,26.063289,27.452055,33.676322
IRS,10.530500,8.817976,12.414325,13.109084,17.433095,9.404008,6.158406,12.779684,11.959325,8.011116,9.425476,14.302829,16.273068,16.665929,24.185862
TALK.L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,136.276852,136.248016,178.801587,258.512649,305.643254,310.179366,211.463386,178.401163
MSPYX,NaN,NaN,NaN,11.346627,11.142540,10.375833,10.457610,10.813360,10.750635,11.663586,11.023373,11.242789,11.365857,11.466126,11.099080
SJ8.MU,NaN,NaN,NaN,11.261667,8.519127,6.531590,6.371300,12.258013,29.729533,28.224478,36.144328,22.813037,24.284623,17.227169,17.591786
0303.HK,11.956818,13.152299,19.583469,38.933400,59.039634,38.519918,54.180478,83.305400,84.078189,90.429000,105.294262,100.252632,96.951220,89.317073,98.114881
ANTM,38.528499,45.859802,70.039623,75.366893,81.085000,48.830397,49.031594,56.483676,69.258810,62.867450,80.569286,111.832829,147.797849,134.385336,170.243334
VKTX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.525568,1.342737,1.366345
DGX,38.434250,43.196845,50.925913,55.232749,52.806190,48.981826,53.755139,52.368617,55.283651,59.103546,58.635476,60.558685,70.440438,80.406996,100.749425
ATGYX,25.869500,26.185595,28.812936,31.966494,34.180873,24.713770,20.114143,24.661581,27.614881,27.662271,36.046905,43.618526,48.935299,48.931700,53.118851
035080.KQ,2758.696682,2051.893008,4614.145226,7148.666972,5795.079755,4404.571429,6234.212598,5103.869048,5319.190283,6211.400000,9145.510204,11107.398374,10496.048387,6609.085366,5116.726190
^CEX,194.836001,202.757976,225.389841,236.457410,290.555873,279.319841,227.799124,266.537312,310.329803,341.529123,413.529524,495.823545,489.373028,487.391463,545.119541
EFX,24.837500,25.891429,34.627341,36.537530,39.048690,32.161865,27.289522,32.643715,35.422183,47.704542,61.905516,74.607131,100.167849,121.584427,133.869425
AOL-U.TI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CIT-U.TI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
^UMIAMIFL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
JPM-PB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
KCT.V,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NMBS.KL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CPWFF8.EX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FLINGX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1880.HK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [64]:

newDataFrame= pandas.DataFrame(columns=['Symbol','Date','Price'])
k =0
for i in range(len(finalData2)) : 
    ts = finalData2.index[i]
    for j in range(len(finalData2.iloc[i])): 
        time_frame = pandas.to_datetime(str(finalData2.columns.values[j]))
        date = time_frame.strftime('%Y-%m-%d')
        newDataFrame.loc[k]=( ts,  date , finalData2.iloc[i][j])
        k=k+1

In [78]:
newDataFrame.head()

  Symbol  Date      Price
1    ADP  2004  34.064935
2    ADP  2005  35.050695
3    ADP  2006  36.863325
4    ADP  2007  40.408635
5    ADP  2008  35.680073

In [66]:
newDataFrame.loc[newDataFrame['Date'] == '2005-01-31', 'Date'] = '2004'
newDataFrame.loc[newDataFrame['Date'] == '2006-01-31', 'Date'] = '2005'
newDataFrame.loc[newDataFrame['Date'] == '2007-01-31', 'Date'] = '2006'
newDataFrame.loc[newDataFrame['Date'] == '2008-01-31', 'Date'] = '2007'
newDataFrame.loc[newDataFrame['Date'] == '2009-01-31', 'Date'] = '2008'
newDataFrame.loc[newDataFrame['Date'] == '2010-01-31', 'Date'] = '2009'
newDataFrame.loc[newDataFrame['Date'] == '2011-01-31', 'Date'] = '2010'
newDataFrame.loc[newDataFrame['Date'] == '2012-01-31', 'Date'] = '2011'
newDataFrame.loc[newDataFrame['Date'] == '2013-01-31', 'Date'] = '2012'
newDataFrame.loc[newDataFrame['Date'] == '2014-01-31', 'Date'] = '2013'
newDataFrame.loc[newDataFrame['Date'] == '2015-01-31', 'Date'] = '2014'
newDataFrame.loc[newDataFrame['Date'] == '2016-01-31', 'Date'] = '2015'
newDataFrame.loc[newDataFrame['Date'] == '2017-01-31', 'Date'] = '2016'
newDataFrame.loc[newDataFrame['Date'] == '2018-01-31', 'Date'] = '2017'

In [ ]:
#Change the Date to year before. ignoring 2004.

In [75]:
newDataFrame = newDataFrame[newDataFrame['Date'] != '2004-01-31']

In [77]:
#Save Data to a file
newDataFrame.to_csv('Assignment3_FinanceFinalData.csv', index=True, encoding='utf-8')

In [17]:
data_ticker = pandas.DataFrame(arrTicker) 
data_ticker['Ticker_Symbol'] = pandas.Series(arrTicker, index=data_ticker.index)

In [19]:
file1['Ticker_symbol']= data_ticker['Ticker_Symbol']

In [20]:
file1 = file1.dropna(axis=0,how='any')

In [21]:
file1.head()

,Entity,Year,Records Lost,Organisation,Method of Leak,Data Sensitivity,Ticker_symbol
0,AOL,2004,92000000,web,inside job,E-mail Address or Online Information,AOL-U.TI
1,Automatic Data Processing,2005,125000,financial,poor security,SSN/Personal Details,ADP
3,Citigroup,2005,3900000,financial,lost / stolen device,Credit Card Information,CIT-U.TI
5,Hewlett Packard,2006,200000,"tech, retail",lost / stolen device,SSN/Personal Details,HPQ
7,KDDI,2006,4000000,telecoms,hacked,E-mail Address or Online Information,KDDIY

In [22]:
file1.to_csv('Assignment_FinanceData.csv', index=False, encoding='utf-8')

Data breaches are not punished by stock market as long as the company is well received or followed by customers. Facebook is the classic example, even when there was a data breach, the stock price of Facebook never really came down and was always increasing because of its popularity and ever increasing user base.

Tableau Public link - https://public.tableau.com/profile/aashreya.agasthya.kundurthy#!/vizhome/assignment3_1_1/Dashboard1?publish=yes

The dashboard shows the graph of stock price of Facebook. It has information about how the data was lost. It doesn't show the exact time when the breach happened as only the whole year is taken into consideration.