Import Pandas and import file 'Assignment_2017.csv' that contains the Data.

In [1]:
import pandas

In [2]:
file1 = pandas.read_csv('Assignment1_2017.csv')

In [3]:
file1.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,Entity,alternative name,story,YEAR,records lost,ORGANISATION,METHOD OF LEAK,interesting story,NO OF RECORDS STOLEN,DATA SENSITIVITY,UNUSED,UNUSED,Exclude,NaN,1st source link,2nd source link,3rd source,source name
1,NaN,NaN,Elaboration if there's an interesting story or...,"years are encoded (0=2004, 8 = 2012, 9 = 2013,...","(use 3m, 4m, 5m or 10m to approximate unknown ...",NaN,NaN,NaN,"(use 3m, 4m, 5m or 10m to approximate unknown ...",1. Just email address/Online information 20 SS...,NaN,NaN,Show this item in the viz?,NaN,NaN,NaN,NaN,NaN
2,AOL,American Online,A former America Online software engineer stol...,0,92000000,web,inside job,NaN,92000000,1,NaN,NaN,NaN,NaN,http://money.cnn.com/2004/06/23/technology/aol...,http://www.msnbc.msn.com/id/8985989/#.UFcN8RgUwaA,NaN,CNN
3,Automatic Data Processing,"Business outsourcing, payrolls, benefits",NaN,1,125000,financial,poor security,NaN,130000,20,NaN,NaN,NaN,NaN,http://abcnews.go.com/Technology/story?id=2160...,NaN,NaN,ABC
4,Ameritrade Inc.,Computer backup tape containing personal infor...,online broker,1,200000,financial,lost / stolen device,NaN,200000,20,NaN,NaN,NaN,NaN,http://www.nbcnews.com/id/7561268/,NaN,NaN,NaN

Drop Unwanted Columns

In [4]:
file1.drop(['Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13'], axis= 1, inplace= True)

In [5]:
file1.loc[file1['Unnamed: 3'] == '0', 'Unnamed: 3'] = '2004'
file1.loc[file1['Unnamed: 3'] == '1', 'Unnamed: 3'] = '2005'
file1.loc[file1['Unnamed: 3'] == '2', 'Unnamed: 3'] = '2006'
file1.loc[file1['Unnamed: 3'] == '3', 'Unnamed: 3'] = '2007'
file1.loc[file1['Unnamed: 3'] == '4', 'Unnamed: 3'] = '2008'
file1.loc[file1['Unnamed: 3'] == '5', 'Unnamed: 3'] = '2009'
file1.loc[file1['Unnamed: 3'] == '6', 'Unnamed: 3'] = '2010'
file1.loc[file1['Unnamed: 3'] == '7', 'Unnamed: 3'] = '2011'
file1.loc[file1['Unnamed: 3'] == '8', 'Unnamed: 3'] = '2012'
file1.loc[file1['Unnamed: 3'] == '9', 'Unnamed: 3'] = '2013'
file1.loc[file1['Unnamed: 3'] == '10', 'Unnamed: 3'] = '2014'
file1.loc[file1['Unnamed: 3'] == '11', 'Unnamed: 3'] = '2015'
file1.loc[file1['Unnamed: 3'] == '12', 'Unnamed: 3'] = '2016'
file1.loc[file1['Unnamed: 3'] == '13', 'Unnamed: 3'] = '2017'
file1.loc[file1['Unnamed: 3'] == '14', 'Unnamed: 3'] = '2017'
file1

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,Entity,alternative name,story,YEAR,records lost,ORGANISATION,METHOD OF LEAK,interesting story,NO OF RECORDS STOLEN,DATA SENSITIVITY,1st source link,2nd source link,3rd source,source name
1,NaN,NaN,Elaboration if there's an interesting story or...,"years are encoded (0=2004, 8 = 2012, 9 = 2013,...","(use 3m, 4m, 5m or 10m to approximate unknown ...",NaN,NaN,NaN,"(use 3m, 4m, 5m or 10m to approximate unknown ...",1. Just email address/Online information 20 SS...,NaN,NaN,NaN,NaN
2,AOL,American Online,A former America Online software engineer stol...,2004,92000000,web,inside job,NaN,92000000,1,http://money.cnn.com/2004/06/23/technology/aol...,http://www.msnbc.msn.com/id/8985989/#.UFcN8RgUwaA,NaN,CNN
3,Automatic Data Processing,"Business outsourcing, payrolls, benefits",NaN,2005,125000,financial,poor security,NaN,130000,20,http://abcnews.go.com/Technology/story?id=2160...,NaN,NaN,ABC
4,Ameritrade Inc.,Computer backup tape containing personal infor...,online broker,2005,200000,financial,lost / stolen device,NaN,200000,20,http://www.nbcnews.com/id/7561268/,NaN,NaN,NaN
5,Citigroup,NaN,Blame the messenger! A box of computer tapes c...,2005,3900000,financial,lost / stolen device,y,3900000,300,http://www.nytimes.com/2005/06/07/business/07d...,NaN,NaN,NY Times
6,Cardsystems Solutions Inc.,"Third-party payment processor for Visa, Master...",CardSystems was fingered by MasterCard after i...,2005,40000000,financial,hacked,y,40000000,300,http://www.msnbc.msn.com/id/8260050/ns/technol...,NaN,NaN,MSNBC
7,Hewlett Packard,NaN,Laptop lost/stolen containing employee data: n...,2006,200000,"tech, retail",lost / stolen device,y,200000,20,http://news.cnet.com/Laptop-with-HP-employee-d...,NaN,NaN,NaN
8,Countrywide Financial Corp,Mortgage financer,NaN,2006,2600000,financial,inside job,NaN,2600000,300,http://www.idtheftcenter.org/artman2/publish/l...,NaN,NaN,ITRC
9,KDDI,Japanese telecommunications operator,"Press report: ""Tokyo police have arrested two ...",2006,4000000,telecoms,hacked,y,4000000,1,http://www.computerworld.com/s/article/9001150...,NaN,NaN,Computer World
10,"T-Mobile, Deutsche Telecom",NaN,Thieves got their hands on a storage device wi...,2006,17000000,telecoms,lost / stolen device,NaN,17000000,1,http://www.datalossdb.org,http://www.informationweek.com/security/attack...,NaN,Data Loss Database
11,AOL,American Online,Durp. AOL VOLUNTARILY released search data for...,2006,20000000,web,accidentally published,y,20000000,1,http://techcrunch.com/2006/08/06/aol-proudly-r...,NaN,NaN,Tech Crunch
12,US Dept of Vet Affairs,NaN,The Veterans Affairs Department agreed to pay ...,2006,26500000,"government, military",lost / stolen device,NaN,26500000,20,http://gcn.com/Articles/2009/02/02/VA-data-bre...,NaN,NaN,NaN
13,Texas Lottery,NaN,"Data on more than 89,000 lottery winners (incl...",2007,89000,government,inside job,NaN,90000,20,http://www.idtheftcenter.org/artman2/publish/l...,NaN,NaN,ITRC
14,City and Hackney Teaching Primary Care Trust,NaN,Heavily encrypted disks containing details of ...,2007,160000,government,lost / stolen device,NaN,160000,20,http://www.computerweekly.com/news/2240104003/...,NaN,NaN,NaN
15,Gap Inc,NaN,Stolen laptop which contained social security ...,2007,800000,retail,lost / stolen device,NaN,800000,20,http://www.pcworld.com/article/137865/article....,NaN,NaN,PC World
16,Compass Bank,NaN,A former employee stole a hardrive containing ...,2007,1000000,financial,inside job,y,1000000,300,http://www.idtheftcenter.org/artman2/publish/l...,http://www.computerworld.com/s/article/9072198...,NaN,ITRC
17,Monster.com,Jobs website,A trojan virus stole log-ins that were used to...,2007,1600000,web,hacked,y,1600000,20,http://news.bbc.co.uk/1/hi/6956349.stm,NaN,NaN,BBC
18,Driving Standards Agency,NaN,Hard disk with details of candidates for the d...,2007,3000000,government,lost / stolen device,NaN,3000000,20,http://news.bbc.co.uk/1/hi/uk_politics/7147715...,NaN,NaN,NaN
19,"Driving Standards Agency,",Details of candidates for the driving theory t...,NaN,2007,3000000,government,lost / stolen device,NaN,3000000,20,http://news.bbc.co.uk/1/hi/uk_politics/7147715...,NaN,NaN,NaN
20,Hannaford Brothers Supermarket Chain,"Delhaize Group: Hannaford Bros, Sweetbay, Food...",An estimated 4.2 million credit and debit card...,2007,4200000,retail,hacked,NaN,4200000,300,http://www.idtheftcenter.org/artman2/publish/l...,NaN,NaN,ITRC
21,TD Ameritrade,US online broker,TD Ameritrade settled a class action lawsuit t...,2007,6300000,financial,hacked,NaN,6300000,1,http://www.wired.com/threatlevel/2008/07/ameri...,NaN,NaN,Wired
22,Fidelity National Information Services,Employee sold customer information to a data b...,NaN,2007,8500000,financial,inside job,NaN,8500000,300,http://www.pcworld.com/article/135117/article....,NaN,NaN,NaN
23,Dai Nippon Printing,Japanese printing company,A former contractor of Dai Nippon Printing Com...,2007,8637405,retail,inside job,NaN,8600000,1,http://usatoday30.usatoday.com/tech/news/compu...,NaN,NaN,USA Today
24,UK Revenue & Customs,HMRC,A set of discs containing confidential details...,2007,25000000,government,lost / stolen device,NaN,25000000,1,http://news.bbc.co.uk/2/hi/uk_news/7103911.stm,NaN,NaN,BBC News
25,TK / TJ Maxx,Largest retail breach to date,Hackers hacked a Minnesota store wifi network ...,2007,94000000,retail,hacked,NaN,94000000,300,http://www.zdnet.com/wi-fi-hack-caused-tk-maxx...,http://www.msnbc.msn.com/id/17871485/ns/techno...,NaN,ZD Net
26,Service Personnel and Veterans Agency (UK),NaN,Stolen USBs containing personal information ab...,2008,50500,government,lost / stolen device,NaN,50000,20,http://news.bbc.co.uk/1/hi/england/gloucesters...,NaN,NaN,NaN
27,Stanford University,NaN,Tens of thousands of past and current Stanford...,2008,72000,academic,lost / stolen device,NaN,72000,20,http://www.idtheftcenter.org/artman2/publish/l...,http://www.sfgate.com/bayarea/article/Stanford...,NaN,ITRC
28,UK Home Office,NaN,PA Consulting lost an unencrypted memory stick...,2008,84000,government,lost / stolen device,NaN,84000,20,http://en.wikipedia.org/wiki/List_of_UK_govern...,NaN,NaN,NaN
29,AT&T,NaN,A laptop was stolen from a car containing unen...,2008,113000,telecoms,lost / stolen device,y,100000,1,http://www.idtheftcenter.org/artman2/publish/l...,NaN,NaN,ITRC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225,uTorrent,NaN,"It's unclear what data has been breached, exac...",2016,35000,web,hacked,NaN,35000,1,https://torrentfreak.com/utorrent-forums-hacke...,NaN,NaN,NaN
226,Banner Health,NaN,Hackers gained access to payment card data via...,2016,3700000,healthcare,hacked,NaN,3700000,300,https://www.bannerhealth.com/news/2016/08/bann...,NaN,NaN,NaN
227,Privatization Agency of the Republic of Serbia,NaN,A text file with personal data and financial d...,2016,5190396,government,accidentally published,NaN,519396,20,http://www.shareconference.net/en/defense/pers...,NaN,NaN,NaN
228,Quest Diagnostics,NaN,"Nov. The stolen data contained names, DOBs, la...",2017,34000,healthcare,hacked,NaN,34000,4000,http://newsroom.questdiagnostics.com/2016-12-1...,NaN,NaN,NaN
229,Three,Three mobile company in the UK,Hackers broke into Three's customer database w...,2017,200000,telecoms,hacked,NaN,200000,20,http://www.threemediacentre.co.uk/news/2017/ha...,NaN,NaN,NaN
230,Wonga,NaN,Apr. Customers from the UK and Poland look to ...,2017,270000,financial,hacked,NaN,270000,50000,https://www.theguardian.com/business/2017/apr/...,NaN,NaN,NaN
231,PayAsUGym,NaN,Dec. Fitness website hacked & email address pu...,2017,300000,web,hacked,NaN,300000,1,http://www.bbc.co.uk/news/technology-38350987,NaN,NaN,NaN
232,Red Cross Blood Service,NaN,Info leaked includes data about 'at risk sexua...,2017,550000,healthcare,accidentally published,NaN,550000,4000,http://www.abc.net.au/news/2016-10-28/red-cros...,NaN,NaN,NaN
233,DaFont,Font sharing site,May. Apparently the hacker found out others we...,2017,700000,web,hacked,NaN,700000,4000,http://www.zdnet.com/article/font-sharing-site...,NaN,NaN,NaN
234,Brazzers,Porn site,"Sept. 'The data contains 790,724 unique email ...",2017,790724,web,hacked,NaN,790724,4000,http://motherboard.vice.com/read/nearly-800000...,NaN,NaN,NaN
235,Snapchat,NaN,Apr. Indian hackers apparently leaked data the...,2017,1700000,app,hacked,NaN,1700000,1,http://www.bgr.in/news/indian-hacker-group-lea...,NaN,NaN,NaN
236,Bell,NaN,Somebody claiming to be behind the attack has ...,2017,1900000,telecoms,hacked,NaN,1900000,1,http://www.cbc.ca/beta/news/technology/bell-da...,NaN,NaN,NaN
237,Cellebrite,NaN,Cellebrite's main product is a device that rip...,2017,3000000,tech,hacked,y,3000000,20,http://motherboard.vice.com/read/hacker-steals...,NaN,NaN,NaN
238,Clinton campaign,NaN,NaN,2017,5000000,government,hacked,NaN,5000000,20,https://techcrunch.com/2016/07/29/clinton-camp...,NaN,NaN,NaN
239,ClixSense,NaN,Sept. The information stolen contains username...,2017,6600000,web,hacked,NaN,6600000,50000,http://www.digitaltrends.com/computing/clixsen...,NaN,NaN,NaN
240,Lynda.com,owned by LinkedIn,Hackers breached a database that held records ...,2017,9500000,web,hacked,NaN,9500000,1,https://www.neowin.net/news/microsoft-owned-li...,NaN,NaN,NaN
241,Interpark,NaN,July. South Korean police are blaming North Ko...,2017,10000000,web,hacked,NaN,10000000,20,http://www.nytimes.com/2016/07/29/world/asia/n...,NaN,NaN,NaN
242,Zomato,Restaurants & events,The hacker is selling the stolen dataset for a...,2017,17000000,web,hacked,NaN,17000000,4000,https://www.hackread.com/zomato-hacked-17-mill...,NaN,NaN,NaN
243,Yahoo,NaN,User accounts have been hacked using forged co...,2017,32000000,web,hacked,NaN,32000000,4000,https://www.cnet.com/news/yahoo-says-forged-co...,NaN,NaN,NaN
244,Weebly,NaN,"Feb. Usernames, passwords and IP addresses sto...",2017,43000000,web,hacked,NaN,43000000,4000,https://techcrunch.com/2016/10/20/weebly-hacke...,NaN,NaN,NaN
245,Dailymotion,video sharing site,"85.2m email addresses extracted, but only 18.3...",2017,85200000,web,hacked,NaN,85200000,1,http://www.zdnet.com/article/dailymotion-hack-...,NaN,NaN,NaN
246,Friend Finder Network,"Parent company of Adult Friend Finder , Cams.c...","Usernames, email addresses, passwords for site...",2017,412000000,web,hacked,NaN,412000000,1,http://www.zdnet.com/article/adultfriendfinder...,https://www.leakedsource.com/blog/friendfinder,NaN,ZDNet / LeakedSource
247,River City Media,Spam operator,A dodgy backup has allegedly resulted in over ...,2017,1370000000,web,accidentally published,NaN,700000000,20,https://betanews.com/2017/03/06/river-city-med...,NaN,NaN,NaN
248,Telegram,Instant messaging service,"Despite Telegram's claims of super security, t...",2017,15000000,tech,hacked,NaN,15000000,1,http://venturebeat.com/2016/08/02/hackers-brea...,NaN,NaN,NaN
249,Waterly,App for paying water bills,Jan 2017. Israel-based app contained a vulnera...,2017,1000000,app,poor security,NaN,1000000,300,https://www.databreaches.net/waterly-app-poten...,NaN,NaN,NaN
250,CEX,NaN,A misconfigured spambot leaked full contact in...,2017,2000000,retail,accidentally published,NaN,2000000,300,https://www.theguardian.com/technology/2017/au...,NaN,NaN,NaN
251,Swedish Transport Agency,NaN,Information about all vehicles in the country ...,2017,3000000,government,poor security,y,3000000,50000,https://www.thelocal.se/20170717/swedish-autho...,NaN,NaN,NaN
252,Instagram,NaN,A bug exposed user's contact information. Inst...,2017,6000000,web,hacked,NaN,6000000,1,https://www.theverge.com/2017/9/1/16244304/ins...,NaN,NaN,NaN
253,Equifax,NaN,"If you have a credit report, there’s a good ch...",2017,143000000,financial,hacked,y,143000000,50000,https://www.consumer.ftc.gov/blog/2017/09/equi...,NaN,NaN,NaN
254,Spambot,NaN,A misconfigured spambot has leaked over 7m rec...,2017,711000000,web,poor security,NaN,711000000,4000,https://www.theguardian.com/technology/2017/au...,NaN,NaN,NaN

In [ ]:
Change Column names

In [6]:
file1.rename(columns={'Unnamed: 1': 'Alternative Name'}, inplace=True)
file1.rename(columns={'Unnamed: 0': 'Entity','Unnamed: 2': 'Story', 'Unnamed: 3': 'Year','Unnamed: 4': 'Records Lost','Unnamed: 5': 'Organisation','Unnamed: 6': 'Method of Leak','Unnamed: 7': 'Intresting Story','Unnamed: 8': 'No of Records Stolen','Unnamed: 9': 'Data Sensitivity','Unnamed: 14': '1st source link','Unnamed: 15': '2nd source link','Unnamed: 16': '3rd source','Unnamed: 17': 'Source Name'}, inplace=True)

In [7]:
file1.drop(file1.index[0], inplace= True)

In [8]:
file1.head()

,Entity,Alternative Name,Story,Year,Records Lost,Organisation,Method of Leak,Intresting Story,No of Records Stolen,Data Sensitivity,1st source link,2nd source link,3rd source,Source Name
1,NaN,NaN,Elaboration if there's an interesting story or...,"years are encoded (0=2004, 8 = 2012, 9 = 2013,...","(use 3m, 4m, 5m or 10m to approximate unknown ...",NaN,NaN,NaN,"(use 3m, 4m, 5m or 10m to approximate unknown ...",1. Just email address/Online information 20 SS...,NaN,NaN,NaN,NaN
2,AOL,American Online,A former America Online software engineer stol...,2004,92000000,web,inside job,NaN,92000000,1,http://money.cnn.com/2004/06/23/technology/aol...,http://www.msnbc.msn.com/id/8985989/#.UFcN8RgUwaA,NaN,CNN
3,Automatic Data Processing,"Business outsourcing, payrolls, benefits",NaN,2005,125000,financial,poor security,NaN,130000,20,http://abcnews.go.com/Technology/story?id=2160...,NaN,NaN,ABC
4,Ameritrade Inc.,Computer backup tape containing personal infor...,online broker,2005,200000,financial,lost / stolen device,NaN,200000,20,http://www.nbcnews.com/id/7561268/,NaN,NaN,NaN
5,Citigroup,NaN,Blame the messenger! A box of computer tapes c...,2005,3900000,financial,lost / stolen device,y,3900000,300,http://www.nytimes.com/2005/06/07/business/07d...,NaN,NaN,NY Times

In [ ]:
Drop Unwanted Rows

In [9]:
file1.drop(file1.index[0], inplace= True)
file1.head()

,Entity,Alternative Name,Story,Year,Records Lost,Organisation,Method of Leak,Intresting Story,No of Records Stolen,Data Sensitivity,1st source link,2nd source link,3rd source,Source Name
2,AOL,American Online,A former America Online software engineer stol...,2004,92000000,web,inside job,NaN,92000000,1,http://money.cnn.com/2004/06/23/technology/aol...,http://www.msnbc.msn.com/id/8985989/#.UFcN8RgUwaA,NaN,CNN
3,Automatic Data Processing,"Business outsourcing, payrolls, benefits",NaN,2005,125000,financial,poor security,NaN,130000,20,http://abcnews.go.com/Technology/story?id=2160...,NaN,NaN,ABC
4,Ameritrade Inc.,Computer backup tape containing personal infor...,online broker,2005,200000,financial,lost / stolen device,NaN,200000,20,http://www.nbcnews.com/id/7561268/,NaN,NaN,NaN
5,Citigroup,NaN,Blame the messenger! A box of computer tapes c...,2005,3900000,financial,lost / stolen device,y,3900000,300,http://www.nytimes.com/2005/06/07/business/07d...,NaN,NaN,NY Times
6,Cardsystems Solutions Inc.,"Third-party payment processor for Visa, Master...",CardSystems was fingered by MasterCard after i...,2005,40000000,financial,hacked,y,40000000,300,http://www.msnbc.msn.com/id/8260050/ns/technol...,NaN,NaN,MSNBC

In [ ]:
Export Data to a New File

In [13]:
file1.to_csv('Cleaned_Data.csv')